#!/bin/sh

regexp="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z]+\))(!)?:( [a-z]+)+$"

msg=$(head -1 $1)

if [[ ! $msg =~ $regexp ]]; then
  echo $msg
  echo $regexp
  echo -e "\n\e[1m\e[31m[INVALID COMMIT MESSAGE]"
  echo -e "------------------------\033[0m\e[0m"
  echo -e "\e[1mValid types:\e[0m \e[34m${types[@]}\033[0m"
  echo -e "\e[1mMax length (first line):\e[0m \e[34m$max_length\033[0m"
  echo -e "\e[1mMin length (first line):\e[0m \e[34m$min_length\033[0m\n"

  # exit with an error
  exit 1
fi